apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-deployment 
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
